CREATE TYPE statuses AS ENUM ('NEW','IN_PROGRESS','DONE');

CREATE TABLE IF NOT EXISTS Tasks (
id SERIAL PRIMARY KEY,
title VARCHAR(30) NOT NULL,
status statuses NOT NULL DEFAULT 'NEW',
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);